
###
#Get de lista completa
GET http://localhost:3000/api/comercio

###
#Get de lista completa con ordenacion pro cif

GET http://localhost:3000/api/comercio?ordenarPorCif=true


###

###


###
#creacion con validacion de datos y con clave publica
POST http://localhost:3000/api/comercio/create HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
  "name": "La ",
  "cif": "B1234783",
  "email": "contacto@s.com",
  "direccion": "Calle , 123, Ciudad Real",
  "telefono": "aaaaa",
  "id": 5
}

###

POST http://localhost:3000/api/comercio/create HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
  "name": "La tieenda ",
  "cif": "B12345678",
  "email": "contacto@latiendita.com",
  "direccion": "Calle , 123, Ciudad Real",
  "telefono": "aaaaa",
  "id": 5
}


###
#actualizacion en base a cif
PUT http://localhost:3000/api/comercio/update/B12345678
Content-Type: application/json

{
  "name": "La Tiendita aaa",
  "direccion": "Calle Nueva, 456, Ciudad Futura",
  "telefono": "900987654"
}

###
#delete de tipo fisico con querys

DELETE http://localhost:3000/api/comercio/delete/B1234783?tipo=fisico
#delete de tipo logico
DELETE http://localhost:3000/api/comercio/delete/B1234783?tipo=logico



###

GET http://localhost:3000/api/users/B12345678





