
###

GET http://localhost:3000/api/users/u

###
#prueba get item




###

POST http://localhost:3000/api/users/usuarios HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
    "name": "HOOOOOOOOOOOOOO",
    "age": "99",
    "email": "pru@gmail.com",
    "password": "prueba",
    "role": "user"
}

###




###



POST http://localhost:3000/api/comercio/crear HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
  "name": "La ",
  "cif": "B1234783",
  "email": "contacto@s.com",
  "direccion": "Calle , 123, Ciudad Real",
  "telefono": "aaaaa",
  "id": 5
}

###


GET http://localhost:3000/api/users/B12345678












#prueba get item

GET http://localhost:3000/api/storage/63fdfbd803e34572e07255fe

###
#prueba get item validator

GET http://localhost:3000/api/storage/63fdfbd803e34572e07255f

###

POST http://localhost:3000/api/tracks HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
    "name": "Ric",
    "album": "Album",
    "cover": "http://tttt.com",
    "artist": {
        "name": "Ric",
        "nickname": "rsurname",
        "nationality": "ES"
    },
    "duration": {
        "start":1,
        "end":2
    },
    "mediaId": "0123456789abcdef01234567"
  
}

###

POST http://localhost:3000/api/storage HTTP/1.1
Content-Type: multipart/form-data; boundary=Boundry

--Boundry
Content-Disposition: form-data; name="image"; filename="img.jpg"
Content-Type: image/jpg

< ./img.jpg
--Boundry--


#prueba validators

POST http://localhost:3000/api/tracks HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
    "dato": "basura",
    "album": "Album",
    "cover": "http://tttt.com",
    "artist": {
        "name": "Ric",
        "nickname": "rsurname",
        "nationality": "ES"
    },
    "duration": {
        "start":1,
        "end":2
    },
    "mediaId": "0123456789abcdef01234567"
  
}

###
#prueba middleware

POST http://localhost:3000/api/tracks HTTP/1.1
Content-Type: application/json
api_key: Api-publica-124

{
    "dato": "basura",
    "name": "Ric Middleware",
    "album": "Album",
    "cover": "http://tttt.com",
    "artist": {
        "name": "Ric",
        "nickname": "rsurname",
        "nationality": "ES"
    },
    "duration": {
        "start":1,
        "end":2
    },
    "mediaId": "0123456789abcdef01234567"
  
}

###
#prueba handleError

POST http://localhost:3000/api/tracks HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
    "dato": "basura",
    "handle error": "huola",
    "name": "Ric",
    "album": "Album",
    "cover": "http://tttt.com",
    "artist": {
        "name": "Ric",
        "nickname": "rsurname",
        "nationality": "ES"
    },
    "duration": {
        "start":1,
        "end":2
    },
    "mediaId": "0123456789abcdef01234567"
  
}

###
#prueba aupdate

PUT http://localhost:3000/api/tracks/63f8b4c551ec87e526f9fe37 HTTP/1.1
Content-Type: application/json
api_key: Api-publica-123

{
    "dato": "basura",
    "name": "Sofia",
    "album": "Album",
    "cover": "http://tttt.com",
    "artist": {
        "name": "Ric",
        "nickname": "rsurname",
        "nationality": "ES"
    },
    "duration": {
        "start":1,
        "end":2
    },
    "mediaId": "0123456789abcdef01234567"
  
}

###
#prueba delete

DELETE http://localhost:3000/api/tracks/63f8b4f551ec87e526f9fe3a

###
#prueba soft delete

DELETE http://localhost:3000/api/tracks/6401f00555d3b717b36d4fe7

###
#prueba delete storage

DELETE http://localhost:3000/api/storage/640738c0da91d68fba45e985

###
#prueba auth

POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "name": "Sofia admin",
    "age": 20,
    "email": "adminyo@test.com",
    "password": "HolaMundo.01"
}

###
#prueba login

POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "adminyo@test.com",
    "password": "HolaMundo.01"
}

###

GET http://localhost:3000/api/tracks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDBiMzMwMTdlNzQxZjdmMTM2YjZjYjMiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNjc4NDU1OTkxLCJleHAiOjE2Nzg0NjMxOTF9.xnRDqQFTLtuxKsM72GHrh1mXAcdUODr5JrCN8KWEUew

###
#prueba check rol 

POST http://localhost:3000/api/tracks HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDEwNmZmNDIyMDVjMmZlZWZlYTE5YTciLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2Nzg4MDA2NjUsImV4cCI6MTY3ODgwNzg2NX0.GuVBLtQSxrqiZKbv3-qXoRoyoTb2UeVlSUIDKzdPues

{
    "name": "Sofia2",
    "album": "admin prueba",
    "cover": "http://tttt.com",
    "artist": {
        "name": "Ric",
        "nickname": "rsurname",
        "nationality": "ES"
    },
    "duration": {
        "start":1,
        "end":2
    },
    "mediaId": "0123456789abcdef01234567"
  
}

###

POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "name": "Sofia ejercicio",
    "age": 20,
    "email": "ejercicio@test.com",
    "password": "HolaMundo.01"
}

###

POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "ejercicio@test.com",
    "password": "HolaMundo.01"
}

###

GET http://localhost:3000/api/users/64107481d643140cb5aabdb8

###
#prueba put check rol

PUT http://localhost:3000/api/users/64107481d643140cb5aabdb8 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDEwNmZmNDIyMDVjMmZlZWZlYTE5YTciLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2Nzg4MDE2ODUsImV4cCI6MTY3ODgwODg4NX0.QPnJf77eLBSjYsMfJQNuCewQv5VYbdEe0o1qf9zTVXI

{
   "name": "Sofia ejercicio",
   "role": "admin"
}

###
###prueba slack

GET http://localhost:3000/ajoaisj.com
